In [ ]:
from google.colab import files
import pandas as pd
import numpy as np

uploaded = files.upload()

file_name = list(uploaded.keys())[0]
raw_df = pd.read_csv(file_name, header=None)

Saving PANEL DATA_csv.csv to PANEL DATA_csv (4).csv

In [ ]:
raw_df.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Name:,Data 8199 USB0::2391 4/18/2023 11:19:08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Owner:,Admin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Comments:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Acquisition Date:,4/18/2023 11:19:09 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,&Instrument:,34972A,Address:,USB0::2391::8199::MY59000288::0::INSTR,Modules:,2,Slot1:,34901A,Slot3:,34901A,NaN,NaN,NaN,NaN
5,Total Channels:,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Channel,Name,Function,Range,Resolution,AdvSettings,Scale,Gain,Offset,Label,Test,Low,High,HWAlarm
7,103,NaN,DC Voltage,Auto,5.5,DC Voltage#10M#1#0.016#Auto#0.001,FALSE,1,0,VDC,Off,0,1,Alarm 1
8,104,NaN,DC Voltage,Auto,5.5,DC Voltage#10M#1#0.016#Auto#0.001,FALSE,1,0,VDC,Off,0,1,Alarm 1
9,105,NaN,DC Voltage,Auto,5.5,DC Voltage#10M#1#0.016#Auto#0.001,TRUE,799.4,0.0781,ADC,Off,0,1,Alarm 1

In [ ]:
len(raw_df)

16384

In [ ]:
start_row = raw_df[raw_df[0].astype(str).str.contains("Scan", na=False)].index[0]
start_row

np.int64(13)

In [ ]:
df = pd.read_csv(
    file_name,
    skiprows=start_row + 1
)

df.head()

,Scan,Time,103 (VDC),Unnamed: 3,104 (VDC),Unnamed: 5,105 (ADC),Unnamed: 7,106 (ADC),Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,10-03-2023 08:50,19.7197,NaN,19.6160,NaN,1.3442,NaN,1.3434,NaN,NaN,NaN,NaN,NaN
1,NaN,10-03-2023 08:55,19.6385,NaN,19.5273,NaN,1.3400,NaN,1.3364,NaN,NaN,NaN,NaN,NaN
2,NaN,10-03-2023 09:00,19.8602,NaN,19.7186,NaN,2.0532,NaN,2.0604,NaN,NaN,NaN,NaN,NaN
3,NaN,10-03-2023 09:05,19.6282,NaN,19.4972,NaN,2.0740,NaN,2.0619,NaN,NaN,NaN,NaN,NaN
4,NaN,10-03-2023 09:10,19.7617,NaN,19.6134,NaN,2.0820,NaN,2.0557,NaN,NaN,NaN,NaN,NaN

In [ ]:
len(df)

16369

In [ ]:
# Remove Unnamed columns
df = df.loc[:, ~df.columns.str.contains("^Unnamed")]

# Remove columns that are fully empty
df = df.dropna(axis=1, how="all")

In [ ]:
len(df)

16369

In [ ]:
df.head()

   Scan              Time  103 (VDC)  104 (VDC)  105 (ADC)  106 (ADC)
0   NaN  10-03-2023 08:50    19.7197    19.6160     1.3442     1.3434
1   NaN  10-03-2023 08:55    19.6385    19.5273     1.3400     1.3364
2   NaN  10-03-2023 09:00    19.8602    19.7186     2.0532     2.0604
3   NaN  10-03-2023 09:05    19.6282    19.4972     2.0740     2.0619
4   NaN  10-03-2023 09:10    19.7617    19.6134     2.0820     2.0557

In [ ]:
df = df.drop(columns=["Scan"], errors="ignore")
df.head()

               Time  103 (VDC)  104 (VDC)  105 (ADC)  106 (ADC)
0  10-03-2023 08:50    19.7197    19.6160     1.3442     1.3434
1  10-03-2023 08:55    19.6385    19.5273     1.3400     1.3364
2  10-03-2023 09:00    19.8602    19.7186     2.0532     2.0604
3  10-03-2023 09:05    19.6282    19.4972     2.0740     2.0619
4  10-03-2023 09:10    19.7617    19.6134     2.0820     2.0557

In [ ]:
#unsoiled-0
#soiled-1
df.columns = [
    "Datetime",
    "V0",
    "V1",
    "C0",
    "C1"
]

df.head()

           Datetime       V0       V1      C0      C1
0  10-03-2023 08:50  19.7197  19.6160  1.3442  1.3434
1  10-03-2023 08:55  19.6385  19.5273  1.3400  1.3364
2  10-03-2023 09:00  19.8602  19.7186  2.0532  2.0604
3  10-03-2023 09:05  19.6282  19.4972  2.0740  2.0619
4  10-03-2023 09:10  19.7617  19.6134  2.0820  2.0557

In [ ]:
num_cols = [
    "V0",
    "V1",
    "C0",
    "C1"
]

df[num_cols] = df[num_cols].apply(pd.to_numeric, errors="coerce")

In [ ]:
len(df)

16369

In [ ]:
from datetime import datetime

In [ ]:
# Force Datetime column to string before string operations
raw_dates = (
    df["Datetime"]
    .astype(str)              # <-- FIX
    .str.strip()
    .str.replace("/", "-", regex=False)
)

raw_dates.head()

0    10-03-2023 08:50
1    10-03-2023 08:55
2    10-03-2023 09:00
3    10-03-2023 09:05
4    10-03-2023 09:10
Name: Datetime, dtype: object

In [ ]:
# Known valid experiment date range
START_DATE = pd.Timestamp("2023-03-10 00:00:00")
END_DATE   = pd.Timestamp("2023-06-20 23:59:59")


START_DATE, END_DATE

(Timestamp('2023-03-10 00:00:00'), Timestamp('2023-06-20 23:59:59'))

In [ ]:
len(df)

16369

In [ ]:
import warnings

parsed_dates = []
prev_time = START_DATE - pd.Timedelta(seconds=1)

with warnings.catch_warnings():
    warnings.simplefilter("ignore", UserWarning)

    for x in raw_dates:
        x = x.strip()

        # Try both interpretations
        dt_df = pd.to_datetime(x, dayfirst=True, errors="coerce")
        dt_mf = pd.to_datetime(x, dayfirst=False, errors="coerce")

        candidates = []

        for d in [dt_df, dt_mf]:
            if pd.notna(d):
                if START_DATE <= d <= END_DATE:
                    if d >= prev_time:
                        candidates.append(d)

        if candidates:
            chosen = min(candidates)
        else:
            # Hard safety to enforce monotonicity
            chosen = prev_time + pd.Timedelta(seconds=1)

        parsed_dates.append(chosen)
        prev_time = chosen

In [ ]:
len(df)

16369

In [ ]:
df["Datetime"] = parsed_dates

df["Datetime"].is_monotonic_increasing

True

In [ ]:
len(df)

16369

In [ ]:
df["Datetime"].min(), df["Datetime"].max()

(Timestamp('2023-03-10 08:50:00'), Timestamp('2023-06-20 10:14:59'))

In [ ]:
df = df.set_index("Datetime")

df.head()

                          V0       V1      C0      C1
Datetime
2023-03-10 08:50:00  19.7197  19.6160  1.3442  1.3434
2023-03-10 08:55:00  19.6385  19.5273  1.3400  1.3364
2023-03-10 09:00:00  19.8602  19.7186  2.0532  2.0604
2023-03-10 09:05:00  19.6282  19.4972  2.0740  2.0619
2023-03-10 09:10:00  19.7617  19.6134  2.0820  2.0557

In [ ]:
# Floor timestamps to hour (keeps only existing hours)
df["hour"] = df.index.floor("h")

# Aggregate ONLY existing hours
hourly_df = df.groupby("hour").mean(numeric_only=True)

hourly_df.head()

                            V0         V1        C0        C1
hour
2023-03-10 08:00:00  19.679100  19.571650  1.342100  1.339900
2023-03-10 09:00:00  19.152545  19.082627  2.144227  2.104691
2023-03-10 10:00:00  19.353600  19.333625  2.277500  2.229750
2023-03-10 11:00:00  19.151892  19.175542  2.270567  2.220933
2023-03-10 12:00:00  18.984883  19.017633  2.251058  2.200825

In [ ]:
len(hourly_df)

1529

In [ ]:
hourly_df.head()

                            V0         V1        C0        C1
hour
2023-03-10 08:00:00  19.679100  19.571650  1.342100  1.339900
2023-03-10 09:00:00  19.152545  19.082627  2.144227  2.104691
2023-03-10 10:00:00  19.353600  19.333625  2.277500  2.229750
2023-03-10 11:00:00  19.151892  19.175542  2.270567  2.220933
2023-03-10 12:00:00  18.984883  19.017633  2.251058  2.200825

In [ ]:
#Prithika's part

In [ ]:
df2 = hourly_df.reset_index()

In [ ]:
unsoiled = df2[["hour", "V0", "C0"]].copy()
unsoiled.columns = ["Datetime", "Voltage", "Current"]
unsoiled["Panel_State"] = 0   # unsoiled

In [ ]:
soiled = df2[["hour", "V1", "C1"]].copy()
soiled.columns = ["Datetime", "Voltage", "Current"]
soiled["Panel_State"] = 1   # soiled

In [ ]:
unsoiled = unsoiled.reset_index(drop=True)
soiled   = soiled.reset_index(drop=True)

In [ ]:
rows = []
min_len = min(len(soiled), len(unsoiled))

for i in range(min_len):
    rows.append(soiled.iloc[i])
    rows.append(unsoiled.iloc[i])

In [ ]:
final_df = pd.DataFrame(rows)

In [ ]:
final_df["Power"] = final_df["Voltage"] * final_df["Current"]

In [ ]:
final_df = final_df[["Datetime", "Voltage", "Current", "Power", "Panel_State"]]

In [ ]:
final_df = final_df.set_index("Datetime")

In [ ]:
final_df = final_df.sort_index()

In [ ]:
final_df.info()
final_df.head()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3058 entries, 2023-03-10 08:00:00 to 2023-06-20 10:00:00
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Voltage      3058 non-null   float64
 1   Current      3058 non-null   float64
 2   Power        3058 non-null   float64
 3   Panel_State  3058 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 119.5 KB

                       Voltage   Current      Power  Panel_State
Datetime
2023-03-10 08:00:00  19.571650  1.339900  26.224054            1
2023-03-10 08:00:00  19.679100  1.342100  26.411320            0
2023-03-10 09:00:00  19.082627  2.104691  40.163032            1
2023-03-10 09:00:00  19.152545  2.144227  41.067410            0
2023-03-10 10:00:00  19.333625  2.229750  43.109150            1

In [ ]:
final_df.reset_index().to_csv(
    "cleaned_panel_data_ps.csv",
    index=False,
)

print("✅ Cleaned hourly dataset saved")

✅ Cleaned hourly dataset saved

In [ ]:
from google.colab import files
files.download("cleaned_panel_data_ps.csv")